<?php
    echo 'Это политика обработки персональных данных <br>
    1. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    2. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    3. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    4. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    5. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    6. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    7. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    8. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    9. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur labore aperiam delectus excepturi fugit consectetur blanditiis facere accusantium itaque ea quas impedit sunt, placeat numquam optio porro, suscipit doloribus ad sapiente modi. Qui, debitis aspernatur? Odit totam cumque facilis! Quos nulla consequatur necessitatibus dicta illum sint, quas eligendi ad eaque. <br>
    
    ';


?>